### ISSUE TITLE
Error: Dynamic require of "../../../common/reactions/ee_1.png" is not supported

### ISSUE THREAD

**Issue by asabadyr** [AgoraIO-Usecase/AgoraChat-UIKit-web#63]
Trying to integrate UIKit to the existing Remix application.
Getting this during rendering of EaseApp.
I have a component wrapping EaseApp in a ClientOnly scope, so it's pure client side rendering without server side.

Tried adding declare module '*.jpg' into global.d.ts but no luck.

Anyone has an idea how to overcome this issue?

**Comment by myZhangDong** [comment]
What did you use to build the project? React or vite

Vite does not support the require syntax

**Comment by myZhangDong** [comment]
Please use version 1.2.0
