### ISSUE TITLE
Are there any way to custom search in ConversationList component base on appUserInfo?

### ISSUE THREAD

**Issue by hoangluke1509** [AgoraIO-Usecase/AgoraChat-UIKit-web#65]

**Comment by myZhangDong** [comment]
You can call cvsStore.setSearchList() method to set the search results to UIKit, and you can decide on how to implement the search function specifically.

**Comment by hoangluke1509** [comment]
> You can call cvsStore.setSearchList() method to set the search results to UIKit, and you can decide on how to implement the search function specifically.

Yeah, I see it in your source code and implement it almost the same way but nothing happens.
I pass a callback that returns false to onSearch props in the ConversationList component to disable the default behavior of the component. Also, I use renderSearch to implement my custom search component and listen to onChange event. In the onChange function, I use cvsStore.setSearchList() and nothing happens even though I just use conversationList not anything from appUserInfo.

**Comment by myZhangDong** [comment]
Sorry, I haven't exposed the control parameter for displaying search results. You can use the cvsStore.setConversation method to control the conversations to be displayed first, and I will add this parameter later.

**Comment by hoangluke1509** [comment]
Thanks, hope you will release it soon. Otherwise, are there any way to disable or hidden some features like translation or edit message?

**Comment by hoangluke1509** [comment]
> Sorry, I haven't exposed the control parameter for displaying search results. You can use the cvsStore.setConversation method to control the conversations to be displayed first, and I will add this parameter later.

I just replace setSearchList to setConversation but nothing happens. I use it in the onChange event:
`
rootStore.conversationStore.setConversation()
`

**Comment by myZhangDong** [comment]
> there

Pass the features parameter to the Provider component, for example, features={{chat: {message: {translate: false, edit: false}}}}, or pass the customAction parameter to the TextMessage component: customAction={visible: true, actions: [{content: 'REPLY'}]}

**Comment by myZhangDong** [comment]
> > Sorry, I haven't exposed the control parameter for displaying search results. You can use the cvsStore.setConversation method to control the conversations to be displayed first, and I will add this parameter later.
> 
> I just replace setSearchList to setConversation but nothing happens. I use it in the onChange event: `rootStore.conversationStore.setConversation()`

I will fix this issue in the next version

**Comment by hoangluke1509** [comment]
> > there
> 
> Pass the features parameter to the Provider component, for example, features={{chat: {message: {translate: false, edit: false}}}}, or pass the customAction parameter to the TextMessage component: customAction={visible: true, actions: [{content: 'REPLY'}]}

I passed the feature parameter to the Provider component, but nothing happens also.

**Comment by myZhangDong** [comment]
> > > there
> > 
> > 
> > Pass the features parameter to the Provider component, for example, features={{chat: {message: {translate: false, edit: false}}}}, or pass the customAction parameter to the TextMessage component: customAction={visible: true, actions: [{content: 'REPLY'}]}
> 
> I passed the feature parameter to the Provider component, but nothing happens also.
Please ensure that you have not passed the messageProps parameter to the Chat component. If a parameter is defined on the component, the global configuration will become invalid

**Comment by hoangluke1509** [comment]
Thank you for clarifying, it works.
