### ISSUE TITLE
Can not send mutiple lines message with default Chat component

### ISSUE THREAD

**Issue by hoangluke1509** [AgoraIO-Usecase/AgoraChat-UIKit-web#66]

**Comment by myZhangDong** [comment]
We will schedule this feature in the plan

**Comment by hoangluke1509** [comment]
Besides, I want to customize the replying messeage component. Is it possible?
![Screenshot 2024-04-23 144234](https://github.com/AgoraIO-Usecase/AgoraChat-UIKit-web/assets/163803525/fd339dc8-f0f0-4f6b-838c-32b4ea1d54da)

**Comment by myZhangDong** [comment]
If you only modify the style, can you directly overwrite the style in UIKIT? If you want to modify the dom structure, can I add another renderRepliedMessage method to meet this requirement?

**Comment by hoangluke1509** [comment]
I'm okay with the style. I think you can provide us some props to customize this (the replying component to show which message user is replying to, the repplied message bubble need to show time,...)

**Comment by hoangluke1509** [comment]
Can you hint me when will you release the next version? including the above features.

**Comment by myZhangDong** [comment]
I will try my best to include the features we have discussed and may propose in the next version, but when will it be released You need to contact our PM.  Perhaps in May?  I'm not sure.

**Comment by hoangluke1509** [comment]
Thanks for hearing my feedback

**Comment by hoangluke1509** [comment]
i see you closed my issues, how do I get the latest changes?

**Comment by myZhangDong** [comment]
The code has been submitted to the dev branch. You can build it yourself and then replace the files in node.modules. The release will take some time

**Comment by hoangluke1509** [comment]
I think I should wait for the final release. Thanks
